version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: 'Dockerfile.${NODE_ENV}'
    container_name: maestro_api
    expose:
      - '3001'
    networks:
      - patkid-bridge
    logging:
      driver: awslogs
      options:
        awslogs-group: '${NODE_ENV}-maestro-backend'
        awslogs-region: 'ap-northeast-2'
        awslogs-stream: 'backend'
networks:
  patkid-bridge:
    external: true
