version: '3.9'

services:
  backend:
    build: ./
    container_name: maestro_api
    expose:
      - '3001'
    networks:
      - patkid-bridge
    logging:
      driver: awslogs
      options:
        awslogs-group: 'maestro-backend'
        awslogs-region: 'ap-northeast-2'
        awslogs-stream: 'backend-${NODE_ENV}'
networks:
  patkid-bridge:
    external: true
